### ISSUE TITLE
[DOCS] Change "AdBlock, Adblock Plus" to "uBlock Origin"

### ISSUE THREAD

**Issue by inson1** [tomasko126/easylistczechandslovak#413] opened 2023-10-19 14:06 UTC
uBlock Origin is more ethical than AdBlock, Adblock Plus

1. reason - AdBlock Plus is trying to be monopol
2. reason - Adlock Plus sells acceptable ads
3. reason - uBlock Origin doesnt want our money, even donations
4. reason - uBlock Origin helps maintainers of block lists by asking users to help them - "If you ever want to contribute something, think about the people working hard to maintain the filter lists you are using, which are available to use by all for free."
5.  reason - you have the power to help (at least little bit)

1) https://www.businessinsider.com/google-microsoft-amazon-taboola-pay-adblock-plus-to-stop-blocking-their-ads-2015-2
2) https://www.businessinsider.com/adblock-gets-sold-acceptable-ads-2015-10
3) https://help.adblockplus.org/hc/en-us/articles/360062733133-Is-Adblock-Plus-the-same-thing-as-AdBlock-#:~:text=AdBlock%20was%20created%20as%20a,Adblock%20Plus%20eventually%20acquired%20AdBlock.
4) https://news.ycombinator.com/item?id=19666350
5) https://github.com/gorhill/uBlock#about

"EasyList Czech and Slovak is an official filter list for AdBlock, Adblock Plus and other ad blockers out there" 
to 
"EasyList Czech and Slovak is an official filter list for uBlock Origin and other ad blockers out there"

**Comment by inson1** [comment] 2023-10-19 14:07
Please delete the bug label, thank you

**Comment by mlnrDev** [comment] 2023-10-19 14:07
thank you for this - personally, I couldn't agree more. the issue is that I do not own this repo, so I'll have to discuss with the owner.

**Comment by inson1** [comment] 2023-10-19 14:09
Thank you :)

Děkuju :)

Mohl jsem to napsat česky co ? xD

**Comment by mlnrDev** [comment] 2023-10-19 14:09
mohol, ale v anglictine sa aj tak vyjadruje lepsie :P

**Comment by tomasko126** [comment] 2023-10-24 11:20
Since this filter list is an official filter list for AdBlock and Adblock Plus (because it's part of the EasyList family), I think that we should not drop their names from the description, but rather add the uBlock Origin wording right there. Such action has been done just a while ago, thus I am closing this issue as resolved.

**Closed by tomasko126** 2023-10-24 11:20 UTC

**Comment by inson1** [comment] 2023-12-18 10:22
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
